parameters:
    database_host: localhost
    database_port: 3306
    database_name: livingnatural
    database_user: livingnatural_admin
    database_password: livingnatural
    mailer_transport: smtp
    mailer_host: 127.0.0.1
    mailer_user: mail
    mailer_password: mail
    secret: e64f7ad60ad0f7ea0ab6746ebca0734ad4eead44
